// Generates docs/RECIPE-REFERENCE.md from the registry.
//
// The catalog is the single source of truth, so the reference cannot drift
// from the code. Run with --check in CI to fail when it is stale.
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { createBuiltinMotionRegistry } from '../src/recipes/builtins.js'

const OUTPUT = resolve(import.meta.dirname, '../docs/RECIPE-REFERENCE.md')

const FAMILY_TITLES = {
  'reveals-entrances': 'Reveals and entrances',
  'split-text-typography': 'Split text and typography',
  'scroll-parallax': 'Scroll and parallax',
  'pinned-storytelling': 'Pinned storytelling',
  'horizontal-galleries': 'Horizontal galleries',
  'hover-focus-pointer': 'Hover, focus and pointer',
  'navigation-overlay': 'Navigation and overlays',
  'media-mask-clip': 'Media, mask and clip',
  'loops-progress-ambient': 'Loops, progress and ambient',
  'flip-layout': 'FLIP and layout',
  'svg-path-morph': 'SVG, path and morph',
  'page-load-route': 'Page load and routing',
}

const OPTIONAL_PLUGINS = new Set(['SplitText', 'Flip', 'DrawSVGPlugin', 'MorphSVGPlugin', 'MotionPathPlugin'])

const registry = createBuiltinMotionRegistry()
const recipes = registry.list()

const escape = (value) => String(value).replace(/\|/g, '\\|')

function parameterRows(recipe) {
  const entries = Object.entries(recipe.parameters)
  if (!entries.length) return '_No parameters._'
  const rows = entries.map(([name, parameter]) => {
    const range = parameter.type === 'number'
      ? `${parameter.min} to ${parameter.max}`
      : parameter.type === 'enum' ? parameter.values.map((value) => `\`${value}\``).join(', ') : '—'
    return `| \`${name}\` | ${parameter.type} | \`${JSON.stringify(parameter.default)}\` | ${range} |`
  })
  return ['| Parameter | Type | Default | Range |', '| --- | --- | --- | --- |', ...rows].join('\n')
}

function slotRows(recipe) {
  const slots = recipe.slots.filter((slot) => slot.name !== 'root')
  if (!slots.length) return '_The root element is the only target._'
  const rows = slots.map((slot) => {
    const selector = slot.selector
    return `| \`${slot.name}\` | \`${escape(selector)}\` | ${slot.required === false ? 'optional' : 'required'} | ${slot.multiple ? 'many' : 'one'} |`
  })
  return ['| Slot | Selector | Required | Count |', '| --- | --- | --- | --- |', ...rows].join('\n')
}

function section(recipe) {
  const optional = recipe.dependencies.filter((name) => OPTIONAL_PLUGINS.has(name))
  const pluginNote = optional.length
    ? `\n> **Needs ${optional.join(', ')}.** Import from \`@syncedco/motion/full\`, or pass the plugin through \`dependencies\`.\n`
    : ''

  return `### \`${recipe.id}\`

${recipe.description} ${recipe.intent}
${pluginNote}
- **Root:** \`${escape(recipe.root.selector)}\`
- **Triggers:** ${recipe.triggers.map((trigger) => `\`${trigger.type}\``).join(', ')}
- **Performance:** ${recipe.performance.class}
- **Reduced motion:** ${recipe.reducedMotion.strategy} — ${recipe.reducedMotion.behavior ?? 'see notes'}
- **Without JavaScript:** ${recipe.noJs.behavior}
- **Accessibility:** ${recipe.accessibility.notes}

${slotRows(recipe)}

${parameterRows(recipe)}

\`\`\`bash
npx synced-motion add ${recipe.id}
\`\`\`
`
}

const families = [...new Set(recipes.map((recipe) => recipe.family))]
const contents = families
  .map((family) => `- [${FAMILY_TITLES[family] ?? family}](#${(FAMILY_TITLES[family] ?? family).toLowerCase().replace(/[^a-z0-9]+/g, '-')})`)
  .join('\n')

const body = families.map((family) => {
  const inFamily = recipes.filter((recipe) => recipe.family === family)
  return `## ${FAMILY_TITLES[family] ?? family}\n\n${inFamily.map(section).join('\n')}`
}).join('\n')

const document = `<!-- Generated by scripts/build-docs.mjs. Do not edit by hand. -->
# Recipe reference

Every registered recipe, generated from the catalog so it cannot drift from the
code. ${recipes.length} recipes across ${families.length} families.

Selectors are shown with the documented \`data-motion-\` prefix. The original
\`data-motion-\` names remain fully supported.

To explore these interactively, run \`npm run gallery\`. To query them from a
script or an agent, use \`npx synced-motion catalog --json\`.

${contents}

${body}`

const check = process.argv.includes('--check')
if (check) {
  let current = ''
  try {
    current = readFileSync(OUTPUT, 'utf8')
  } catch {
    current = ''
  }
  if (current !== document) {
    process.stderr.write('fail docs/RECIPE-REFERENCE.md is stale. Run "npm run docs:build".\n')
    process.exitCode = 1
  } else {
    process.stdout.write(`pass recipe reference documents all ${recipes.length} recipes.\n`)
  }
} else {
  writeFileSync(OUTPUT, document)
  process.stdout.write(`wrote docs/RECIPE-REFERENCE.md (${recipes.length} recipes, ${families.length} families).\n`)
}
